name: Build and Push Docker Image

on:
  push:
    branches:
      - master  
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
            uses: actions/checkout@v2
        - name: Build and Push Docker Image
            uses: docker/build-push-action@v2
            with:
            context: .
            push: true
            tags: vergissberlin/talk-docker:latest
            cache-from: type=registry,ref=vergissberlin/talk-docker:latest
            cache-to: type=inline
